### ISSUE TITLE
Project's firebase 

### ISSUE THREAD

**Issue by telmas** [git-akshat/mini-project#1]
Hi, excellent project. is there any way for you to share the project's firebase? Or the structure? I would like to recreate it.

**Comment by git-akshat** [comment]
@telmas you need to create any structure. Just give necessary permissions in the firebase and connect your project to the firebase.

**Comment by git-akshat** [comment]
Here are some steps to quickly connect firebase with the project

1. Firebase-> authentication ->signin method -> enable login with email/password

2. Firebase -> database -> real-time database -> rules

    Remove old rules and paste the following lines
```
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```

3. Firebase -> storage -> rules -> edit rules

     Remove old lines and add below lines
```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if true;
    }
  }
}
```
4. Download firebase plugin in android studio

5. In android studio goto tools -> firebase
- Connect firebase with an existing or new project
- Add Storage dependency
-  Add database dependency

**Comment by telmas** [comment]
Thank you very much! Was able to get it working.
