### ISSUE TITLE
Send Mail Feature not working?

### ISSUE THREAD

**Issue by shakthi-sagar** [git-akshat/mini-project#2]
I have added the email and password to the config.java file, but still I am not able to send the message through email. The same for BUY and FEEDBACK options.

**Comment by git-akshat** [comment]
Hi @ShakthiSagarM make sure that you have provided necessary permission for your Gmail account (Less secure app access). Also if 2 factor authentication is on you need to turn that off. What I suggest is, don't use your personal gmail account. Use a temporary/dummy email.

![IMG_20210814_105302](https://user-images.githubusercontent.com/31710005/129435066-52be2be1-1f25-43dc-abcd-338dfd23cb34.jpg)


Also you can use dummy email services like yopmail. I haven't tried it but i think it will work without providing any additional permission.

**Comment by shakthi-sagar** [comment]
well, i actually did that. but i couldn't find any messages received . also, we switched from the idea of sending mails to allowing the buyer to call or message the owner. I'll try looking more into it. Thanks for your source code saved my arse XD.
