### ISSUE TITLE
why app is getting crashed??

### ISSUE THREAD

**Issue by Samkit02** [git-akshat/mini-project#3]
whenever i login into yourt  app the app is crashing 

is it becuase i put my google-services.json there or is it some other issue 

even in logs it is not showing any error of why it is crashed so please help me

plzz tell me.

btw nice work creating this app...

**Comment by git-akshat** [comment]
Hi @Samkit02 , that looks like some firebase connectivity issue. You need to provide sign-in permission from your firebase console and also for database access you need to change the Realtime database rules as well.  You can refer to this previous issue on what permissions need to be provided in firebase console.

[https://github.com/git-akshat/mini-project/issues/1#issuecomment-612149057](https://github.com/git-akshat/mini-project/issues/1#issuecomment-612149057)

**Comment by Samkit02** [comment]
hello @git-akshat i have given every permission to the comment you have mentioned but then also it is getting crashed.

**Comment by git-akshat** [comment]
@Samkit02 could you share the logcat logs as a text file to my mail (mr.akshatagarwal26@gmail.com)
