### ISSUE TITLE
Message sending option is not working

### ISSUE THREAD

**Issue by Arnab1999india** [git-akshat/mini-project#4]
Sir can you please help us on the sending message option .In my project at the time of buying a product sending message / sending message is not working, please kindly if u told us how to solve this it will be very helpfull for me.

**Comment by git-akshat** [comment]
Hi @Arnab1999india ,  you just need to provide your email id and password in [Config.java](https://github.com/git-akshat/mini-project/blob/master/app/src/main/java/com/example/valarmorghulis/firebaseauth/Config.java) file. Also you need to grant necessary permission to your google account. Earlier you could just turn on "Less secure app access" in your google account but it is no longer supported. You need to go through this [security changes](https://support.google.com/accounts/answer/6010255?hl=en-GB&dark=1&visit_id=637902682563016990-1808577537&p=less-secure-apps&rd=1&authuser=1#zippy=%2Cuse-an-app-password) and accordingly make changes for your app.
